const Links = [
    {name:"Accordian",path:"#accordian"},
    {name:"Random Color",path:"#randomcolor"},
    {name:"Star rating",path:"#star"},
    {name:"Steper",path:"#steper"},
    {name:"Vs Code",path:"#vscode"},
    {name:"Image Slider",path:"#ImageSlider"},
    {name:"Load More Button",path:"#LoadMoreButton"},
    {name:"Menu UI",path:"#MenuUI"},
    {name:"QR Code Generator",path:"#QRCodeGenerator"},
    {name:"Dark Theme",path:"#DarkTheme"},
    {name:"Scroll Indicator",path:"#ScrollIndicator"},
    {name:"Tabs",path:"#"},
    {name:"Modal Popup",path:"#"},
    {name:"Github Profile Finder",path:"#"},
    {name:"API implementation",path:"#"},
    {name:"Tic Tac Toe",path:"#"},
    {name:"Feature Flag",path:"#"},
    {name:"useFetch",path:"#"},
    {name:"useOnclickOutside",path:"#"},
    {name:"useWindowResize",path:"#"},
    {name:"Weather App",path:"#"},
    {name:"Food Recipe App",path:"#"},
    {name:"Shopping Cart App",path:"#"},
    {name:"Expense Tracker App",path:"#"},
    {name:"Mern Stack Blog App",path:"#"},
]
export default Links;
